<a href="https://colab.research.google.com/github/shriyapg/Pytorch_Tensors/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensors**

*   A torch. Tensor is a multi-dimensional matrix containing elements of a single data type.
*   Similar to Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).
*   Default data type of float32.
*   More suitable for the deep learning than a numpy array.

In [4]:
import torch
import numpy as np

Lists

In [2]:
my_list=[[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

Numpy Arrays

In [10]:
import numpy as np
np1=np.random.rand(3,4)
np1

array([[0.03534669, 0.80936616, 0.15272082, 0.55382702],
       [0.27753921, 0.60551688, 0.43294526, 0.41845554],
       [0.6912099 , 0.13845944, 0.3265939 , 0.70973849]])

In [11]:
np1.dtype

dtype('float64')

Tensors

In [15]:
import torch
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[-0.4251, -0.5678, -0.0138,  0.3189],
        [-2.0630,  0.9165, -1.2816,  2.0004],
        [ 1.4373, -0.7493, -0.1795, -0.0719]])

In [17]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [18]:
##Create tensor out of numpy array
my_tensor=torch.tensor(np1)
my_tensor


tensor([[0.0353, 0.8094, 0.1527, 0.5538],
        [0.2775, 0.6055, 0.4329, 0.4185],
        [0.6912, 0.1385, 0.3266, 0.7097]], dtype=torch.float64)