<a href="https://colab.research.google.com/github/shriyapg/Pytorch_Tensors/blob/main/Tensors_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensor Math Operations**
* Add, Subtract, Multiply, Divide, Remainders, Exponents
* Shothand and Longhand
* Reassignment

In [1]:
import torch
import numpy as np

In [2]:
tensor_a=torch.tensor([1,2,3,4])
tensor_b=torch.tensor([5,6,7,8])

In [3]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [11]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [9]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [14]:
# Sub Longhand
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [16]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [18]:
# Mul Longhand
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [20]:
# Dividend
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [22]:
# Div Longhand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [24]:
# Remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [26]:
# Remainder Longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [29]:
# Exponents / power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [31]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [33]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [35]:
tensor_a

tensor([1, 2, 3, 4])

In [37]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [38]:
tensor_a

tensor([11, 14, 17, 20])